[package]
name = "noorton"
version = "0.1.0"
authors = ["haslersn <sebastian.hasler@gmx.net>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
mcp23x17 = { git = "https://github.com/haslersn/mcp23x17-rs" }
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
